### ISSUE TITLE
Due to the new release of pycares 1.0, the interface changed

### ISSUE THREAD

**Issue by mathieui** [saghul/aiodns#12]
Because the API of pycares changed, the query function now returns a ares_query_simple_result where previously only a string was expected.

I don't know if that was intentional or not, but I consider it a bug for now.

**Comment by saghul** [comment]
@mathieui hi there! Big fan of poezio :-)

The change was intentional, so I'll bump the dependency in aiodns and call it an API change. With the new return type you can access the resolved name as well as the TTL.

**Comment by saghul** [comment]
@mathieui I just released aiodns 1.0.0, which uses pycares 1.0.0: https://github.com/saghul/aiodns/releases/tag/aiodns-1.0.0

I added some clarification to the README. You can now rely on the result objects to be consistent for the future. :+1:

**Comment by mathieui** [comment]
Thanks a lot, I’ll update poezio to use it
