### ISSUE TITLE
Include tests in archive

### ISSUE THREAD

**Issue by FRidh** [saghul/aiodns#13]
Please include the tests in the archive. This makes it more convenient for packages to automatically test their packages.

**Comment by saghul** [comment]
Thanks for the heads up Frederik, I had forgotten to update the MANIFEST.in file when I renamed the test file. It's now fixed and I released 1.0.1 with this fix.

Out of curiosity, what system are you packaging aiodns for?

Thanks!

**Comment by FRidh** [comment]
Great! Someone had it packaged for Nix/NixOS, and I am fixing the automatic testing of the packages now.
