### ISSUE TITLE
DNSError inheritance

### ISSUE THREAD

**Issue by nibrag** [saghul/aiodns#16]
`loop.getaddrinfo` (asyncio) raises `socket.gaierror` (inherited from `OSError`) when it fail.
It might be worth to `aiodns.DNSError` was also inherited from `OSError`?

```
class DNSError(OSError):
     pass
```

**Comment by saghul** [comment]
I don't think so. This is how Python describes such exception: https://docs.python.org/2/library/exceptions.html#exceptions.OSError

This is not a system error, but a DNS related one.
