### ISSUE TITLE
AttributeError: 'DNSResolver' object has no attribute '_channel'

### ISSUE THREAD

**Issue by atindermann08** [saghul/aiodns#26]
Exception ignored in: <bound method DNSResolver.__del__ of <aiodns.DNSResolver object at 0x7fbeae94ca90>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiodns/__init__.py", line 123, in __del__
AttributeError: 'DNSResolver' object has no attribute '_channel'

**Comment by saghul** [comment]
Can you paste a test case?  The `_channel` attribute is created in `__init__` so it should be there unless an assert blows.
