### ISSUE TITLE
Let DNSError inherit OSError to match with stdlib behavior

### ISSUE THREAD

**Issue by achimnol** [saghul/aiodns#30]
Both `socket.getaddrinfo` and `asyncio.BaseEventLoop.getaddrinfo` raises `OSError` when a DNS lookup fails.
It would be more consistent if `aiodns.error.DNSError` is also an instance of `OSError`, setting errno and stringified error message as the current implementation does.

**Comment by saghul** [comment]
I don't think that's a good idea. The returned errors don't necessarily match errno.
