### ISSUE TITLE
SystemError resolving TXT record

### ISSUE THREAD

**Issue by pin3da** [saghul/aiodns#32]
Hello, I was resolving DNS records for some domains and I found an unexpected error resolving the `TXT` record of  `like.com.sa`

Here is a code to reproduce the error

```python
import asyncio
import aiodns

loop = asyncio.get_event_loop()
resolver = aiodns.DNSResolver(loop=loop)
result = loop.run_until_complete(resolver.query('like.com.sa', 'TXT'))
print(result)
```

Thanks

**Comment by saghul** [comment]
What error do you get?

**Comment by pin3da** [comment]
```
Exception ignored in: functools.partial(<function DNSResolver._callback at 0x7fc615986950>, <Future pending cb=[_run_until_complete_cb() at /usr/local/lib/python3.6/asyncio/base_events.py:176]>)
Traceback (most recent call last):
  File "/home/pin3da/py-envs/py36-discovery/lib/python3.6/site-packages/aiodns/__init__.py", line 56, in _callback
    if fut.cancelled():
SystemError: <built-in method cancelled of _asyncio.Future object at 0x7fc615ebbcf8> returned a result with an error set
```

**Comment by saghul** [comment]
Hi there! I could reproduce it. It seems to only happen with that domain, as tests pass. I'll take a look as soon as I can!

**Comment by saghul** [comment]
I think the problem is in pycares.

**Comment by pin3da** [comment]
I found another domain which causes the same problem (maybe helps to see what happens):

`wide.com.es`

**Comment by saghul** [comment]
Thanks!

**Comment by saghul** [comment]
This should fix it: https://github.com/saghul/pycares/pull/57

**Comment by saghul** [comment]
Tests pass, this will be part of the next pycares release. You can alternatively install pycares from master in the meantime. Cheers!

**Comment by pin3da** [comment]
It's working now, thank you very much !

**Comment by steven2308** [comment]
Hi, I have the exact problem just with another domain and MX:

`import asyncio
import aiodns

loop = asyncio.get_event_loop()
resolver = aiodns.DNSResolver(loop=loop)
result = loop.run_until_complete(resolver.query('xn--cardeosapeluqueros-r0b.com', 'MX'))
print(result)
`

I get 
`Exception ignored in: functools.partial(<function DNSResolver._callback at 0x7fc89b406ea0>, <Future pending cb=[_run_until_complete_cb() at /usr/local/lib/python3.6/asyncio/base_events.py:176]>)
Traceback (most recent call last):
  File "/home/steven/Envs/vPandapipe/lib/python3.6/site-packages/aiodns/__init__.py", line 56, in _callback
    if fut.cancelled():
SystemError: <built-in method cancelled of _asyncio.Future object at 0x7fc89bb3b828> returned a result with an error set
`

I'm using aiodns 1.1.1 and pycares 2.3.0

**Comment by steven2308** [comment]
Doing a ns lookup I found this for MX:
`Non-authoritative answer:
xn--cardeosapeluqueros-r0b.com	mail exchanger = 10 carde\241osapeluqueros.com.`
Maybe it's the special character "\241"?
