### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by lphuberdeau** [saghul/aiodns#33]
Following a change in pycares, the TXT records are now provided as byte strings. The change [appears to be intentional](https://github.com/saghul/pycares/commit/1e2f23659f6d38c23e5e741878464f6d8179013c#diff-61d51a325171d97c8a56e59ea525339b).

This results in a behavior change for aiodns depending on if the library is using 2.2.0 or 2.3.0. I would expect the .text property to always return a string.

**Comment by saghul** [comment]
Yes, it was intentional. The reason being that there are many TXT records out there with invalid UTF-8 characters in there, so we cannot make a string out of them. So, from 2.3.0 onwards, TXT records will always be bytes.
