### ISSUE TITLE
`install_requires` collides with `typing` for the standard library

### ISSUE THREAD

**Issue by eigenein** [saghul/aiodns#57]
Hi,

The `install_requires` section in `setup.py` contains `typing` dependency, which at least on my Python 3.7 collides with the standard `typing` and produces false-positive warnings in IDE.

Should it perhaps use [environment markers](https://www.python.org/dev/peps/pep-0496/) to avoid installing the 3rd-party `typing` on the latest Python?

Regards,
Pavel

**Comment by saghul** [comment]
Hi @eigenein yes, this makes sense. Are you up for writing a PR?

**Comment by eigenein** [comment]
Arthur was way faster 👍

**Comment by samuelcolvin** [comment]
Great thanks.

Would be good if we could get a release including this. Unfortunately, it upsets pycharm **a lot**.

**Comment by saghul** [comment]
@samuelcolvin 2.0.0b1 was released with this included.
