### ISSUE TITLE
File IO in setup.py misses explicit file encoding.

### ISSUE THREAD

**Issue by eisensheng** [saghul/aiodns#7]
The current `setup.py` file misses an explicit file encoding declaration for the `README.rst` file and package version detection. These files have the explicit UTF-8 encoding though. This causes the setup process to fail under certain circumstances in certain environments.

**Comment by saghul** [comment]
Doh, missed this one. Should be fixed by https://github.com/saghul/aiodns/commit/1b65499d2cc9d5fc3843a65fe7eb50a1175a8990
