### ISSUE TITLE
too many arguments to function call, expected 6, have 7

### ISSUE THREAD

**Issue by stiko** [saghul/aiodns#72]
I'm getting 
`build/temp.macosx-10.14-x86_64-3.7/_cares.c:2573:55: error: too many arguments to function call, expected 6, have 7`
 on `pip install aiodns`
**pip/python version:** pip 19.0.3 from path/to/venv/lib/python3.7/site-packages/pip-19.0.3-py3.7.egg/pip (python 3.7)
OS: macOS Mojave 10.14.6

**Comment by saghul** [comment]
What pycares version is being installed?

**Comment by stiko** [comment]
None. Trying to install `pycares` produces the same error

**Comment by saghul** [comment]
That's not really possible. aiodns uses pycares to do the actual resolution. Do you have any more output?

**Comment by stiko** [comment]
I think I get it. The error is caused by `pycares`. This is the output
```
ERROR: Command "/usr/local/opt/python@2/bin/python2.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/2y/9jk44j2961195sw0srljt3lm0000gn/T/pip-install-5qMY_s/pycares/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/2y/9jk44j2961195sw0srljt3lm0000gn/T/pip-record-Yb0wrQ/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/2y/9jk44j2961195sw0srljt3lm0000gn/T/pip-install-5qMY_s/pycares/
```
The error is true for both python2/3.

Any idea how to fix this? or is this something for `pycares`?

**Comment by saghul** [comment]
You seem to have c-area installed on your system. This is not supported as the version bundled by pycares is not compatible.

You need to uninstall it first.

**Comment by frmz** [comment]
Any way to install pycares without uninstalling OSX c-ares library? There are a bunch of dependencies on that in brew so its not that easy

**Comment by stiko** [comment]
I ended up not using this repo

**Comment by frmz** [comment]
> I ended up not using this repo

But unfortunately its used by CCXT

**Comment by stiko** [comment]
Try putting it in a Docker container
