### ISSUE TITLE
Convert Type Annotations to Py3 syntax

### ISSUE THREAD

**Issue by cooperlees** [saghul/aiodns#76]
Since this project is now >= Python 3.5 we can move all type annotations to Python 3 syntax except variable annotations (they will need to stay as comments until the project is >= 3.6).

Happy to do the PR one day and also happy if someone else beats me. I did PR #75 to add CI type checking, ensuring master is passing before we convert.

Not sure if there are tools to do this for us, but manual wouldn’t take to long.

**Comment by mimi89999** [comment]
I guess that it would also be good to annotate pycares.

**Comment by cooperlees** [comment]
> I guess that it would also be good to annotate pycares.

For sure. But I feel that should be an issue over at https://github.com/saghul/pycares :)

**Comment by cooperlees** [comment]
Did it: https://github.com/saghul/pycares/issues/112

**Comment by mimi89999** [comment]
I opened a PR :wink:.
