### ISSUE TITLE
Issue a release please

### ISSUE THREAD

**Issue by andrey-utkin** [saghul/aiodns#80]
Please issue a tagged release since there are bugfixes accumulated since last release, to enable distributions to distribute the updates.

https://github.com/saghul/aiodns/issues/71 , which causes Gentoo bug https://bugs.gentoo.org/692720 has been resolved in Sep 2019. Yet the last release of aiodns is from Mar 2019.

Thanks in advance.

**Comment by VonAncken** [comment]
I am also interested in a new release.
Thanks.

**Comment by saghul** [comment]
Sorry for the delay. I'll get one out asap.

**Comment by jloehel** [comment]
> Sorry for the delay. I'll get one out asap.

Any progress on that? I would really appreciate a new release. :-)

**Comment by krishna-veerareddy** [comment]
@saghul Hey any updates on this? Looking forward to a new release :)

**Comment by L1ghtn1ng** [comment]
@saghul Just an fyi need to to have travis test py3.8 as it works fine in that but currently if you try python3.9 you cannot install aiodns so currently the max py version that aiodns can support till it gets fixed is py3.8 and py3.9 release is not to far away, its on beta 5 if I recall correctly

**Comment by eric-spitler** [comment]
Last commit was 14 months ago, last release is nearly 2 years. Is this still being maintained?

This is a dependency in [aiohttp](https://github.com/aio-libs/aiohttp) and the current release still installs `typing` in newer versions of Python despite built-in support.

**Comment by saghul** [comment]
Sorry folks, I'm no longer uso tuuu is package myself and used to maintain it on my spare time.

Since the pandemic started I've been busier than ever and haven't been able to maintain packages such as this one.

I'm happy to give the commit bit to those who would like to help with maintenance / releases.

**Comment by saghul** [comment]
3.0.0 is out: https://pypi.org/project/aiodns/3.0.0/
