### ISSUE TITLE
[2.0.0] will rely on pip typing

### ISSUE THREAD

**Issue by tuxmaster5000** [saghul/aiodns#82]
But since 3.5 it is a part of python itself:
https://pypi.org/project/typing/

**Comment by tuxmaster5000** [comment]
+ /usr/bin/python3 setup.py test
running test
Searching for typing
Reading https://pypi.org/simple/typing/
Download error on https://pypi.org/simple/typing/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'typing' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for typing
error: Could not find suitable distribution for Requirement.parse('typing')
Fehler: Fehler-Status beim Beenden von /var/tmp/rpm-tmp.nZALq0 (%check)
    Fehler-Status beim Beenden von /var/tmp/rpm-tmp.nZALq0 (%check)

**Comment by saghul** [comment]
Wouldn't this have failed? https://travis-ci.org/github/saghul/aiodns/jobs/624358454

**Comment by tuxmaster5000** [comment]
In the git version it is fixed, but 2.0.0 sill contains the broken code.
Because your build use python 3.5 all is fine,

**Comment by saghul** [comment]
3.0.0 is now out: https://pypi.org/project/aiodns/3.0.0/
