### ISSUE TITLE
Use PEP-0561 to indicate to library users that type hints are available

### ISSUE THREAD

**Issue by mathieui** [saghul/aiodns#93]
Hello,

aiodns contains type hints, but code that uses aiodns does not benefit from having it typed, due to the lack of a "py.typed" file in the module root. This should be easily fixed by creating the file and adding it as package data in the setup script.

ref: https://www.python.org/dev/peps/pep-0561/

**Comment by JCHacking** [comment]
Hi @mathieui 
The change is already merged, so you can close this issue as completed.
