### ISSUE TITLE
Import error in termux

### ISSUE THREAD

**Issue by thewhiteh4t** [saghul/aiodns#98]
aiodns version : `v3.0.0`
pycares version : `v4.0.0`

steps to reproduce : 

`python -c "import aiodns"`

Exception : 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/aiodns/__init__.py", line 4, in <module>
    import pycares
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pycares-4.0.0-py3.9-linux-aarch64.egg/pycares/__init__.py", line 2, in <module>
    from ._cares import ffi as _ffi, lib as _lib
ImportError: dlopen failed: cannot locate symbol "getservbyport_r" referenced by "/data/data/com.termux/files/usr/lib/python3.9/site-packages/pycares-4.0.0-py3.9-linux-aarch64.egg/pycares/_cares.cpython-39.so"...
```

**Comment by XniceCraft** [comment]
https://github.com/saghul/pycares/issues/78#issuecomment-445508989 pycares module cause the issue

**Comment by adbenitez** [comment]
having this issue recently

**Comment by Happiness777** [comment]
> pycares fails to install

Same here

**Comment by Happiness777** [comment]
Fixed it by following this:
https://github.com/saghul/pycares/issues/78#issuecomment-445508989

**Comment by Trandaitai1212** [comment]
How to fix 
![Screenshot_20240822-234959](https://github.com/user-attachments/assets/c8511a76-d98b-40be-aebe-02562cd66784)
